-- transactional model
drop table NAPOLITANA_CON_FRITAS.Item_Compra_Auto;
drop table NAPOLITANA_CON_FRITAS.Item_Compra_Autoparte;
drop table NAPOLITANA_CON_FRITAS.Item_Factura_Auto;
drop table NAPOLITANA_CON_FRITAS.Item_Factura_Autoparte;
drop table NAPOLITANA_CON_FRITAS.Compra;
drop table NAPOLITANA_CON_FRITAS.Factura;
drop table NAPOLITANA_CON_FRITAS.Auto;
drop table NAPOLITANA_CON_FRITAS.Autoparte;
drop table NAPOLITANA_CON_FRITAS.Modelo;
drop table NAPOLITANA_CON_FRITAS.Tipo_Transmision;
drop table NAPOLITANA_CON_FRITAS.Tipo_Caja;
drop table NAPOLITANA_CON_FRITAS.Tipo_Auto;
drop table NAPOLITANA_CON_FRITAS.Fabricante;
drop table NAPOLITANA_CON_FRITAS.Cliente;
drop table NAPOLITANA_CON_FRITAS.Sucursal;

-- BI model
DROP TABLE NAPOLITANA_CON_FRITAS.BI_Venta_Autoparte;
DROP TABLE NAPOLITANA_CON_FRITAS.BI_Compra_Autoparte;
DROP TABLE NAPOLITANA_CON_FRITAS.BI_Venta_Auto;
DROP TABLE NAPOLITANA_CON_FRITAS.BI_Compra_Auto;
drop table NAPOLITANA_CON_FRITAS.BI_Autoparte;
drop table NAPOLITANA_CON_FRITAS.BI_Modelo;
drop table NAPOLITANA_CON_FRITAS.BI_Tipo_Transmision;
drop table NAPOLITANA_CON_FRITAS.BI_Tipo_Caja;
drop table NAPOLITANA_CON_FRITAS.BI_Tipo_Auto;
drop table NAPOLITANA_CON_FRITAS.BI_Fabricante;
drop table NAPOLITANA_CON_FRITAS.BI_Sucursal;
drop table NAPOLITANA_CON_FRITAS.BI_Cantidad_Cambios;
drop table NAPOLITANA_CON_FRITAS.BI_Tipo_Motor;
DROP TABLE NAPOLITANA_CON_FRITAS.BI_Cliente;
DROP TABLE NAPOLITANA_CON_FRITAS.BI_Cantidad_Rango;
DROP TABLE NAPOLITANA_CON_FRITAS.BI_Mes;
DROP TABLE NAPOLITANA_CON_FRITAS.BI_Potencia_Rango;

drop schema NAPOLITANA_CON_FRITAS;
