-- Creacion de estructuras
CREATE TABLE gd_esquema.Cliente (
CLIENTE_ID [decimal](18, 0) IDENTITY PRIMARY KEY,
CLIENTE_APELLIDO [nvarchar](255) NULL,
CLIENTE_NOMBRE [nvarchar](255) NULL,
CLIENTE_DIRECCION [nvarchar](255) NULL,
CLIENTE_DNI [decimal](18, 0),
CLIENTE_FECHA_NAC [datetime2](3) NULL,
CLIENTE_MAIL [nvarchar](255) NULL
);

CREATE TABLE gd_esquema.Sucursal (
SUCURSAL_ID [decimal](18, 0) PRIMARY KEY,
SUCURSAL_DIRECCION [nvarchar](255) NULL,
SUCURSAL_MAIL [nvarchar](255) NULL,
SUCURSAL_TELEFONO [decimal](18, 0) NULL,
SUCURSAL_CIUDAD [nvarchar](255) NULL
);

CREATE TABLE gd_esquema.Tipo_Transmision (
TIPO_TRANSMISION_CODIGO decimal(18,0) PRIMARY KEY,
TIPO_TRANSMISION_DESC nvarchar(255)
);

CREATE TABLE gd_esquema.Tipo_Caja (
TIPO_CAJA_CODIGO decimal(18,0) PRIMARY KEY,
TIPO_CAJA_DESC nvarchar(255)
);

CREATE TABLE gd_esquema.Tipo_Auto (
TIPO_AUTO_CODIGO decimal(18,0) PRIMARY KEY,
TIPO_AUTO_DESC nvarchar(255)
);

CREATE TABLE gd_esquema.Fabricante (
FABRICANTE_ID decimal(18,0) IDENTITY PRIMARY KEY,
FABRICANTE_NOMBRE nvarchar(255) 
);

CREATE TABLE gd_esquema.Modelo (
MODELO_CODIGO decimal(18,0) PRIMARY KEY,
MODELO_NOMBRE nvarchar(255),
MODELO_POTENCIA decimal(18,0),
MODELO_FABRICANTE decimal(18,0),
CONSTRAINT FK_MODELO_FABRICANTE FOREIGN KEY (MODELO_FABRICANTE) REFERENCES gd_esquema.Fabricante(FABRICANTE_ID)
);

CREATE TABLE gd_esquema.Auto (
AUTO_ID decimal(18,0) IDENTITY PRIMARY KEY,
AUTO_NRO_CHASIS nvarchar(50),
AUTO_NRO_MOTOR nvarchar(50),
AUTO_PATENTE nvarchar(50),
AUTO_FECHA_ALTA datetime2(3),
AUTO_CANT_KMS decimal(18,0),
AUTO_MODELO decimal(18,0),
AUTO_TIPO_TRANSMISION decimal(18,0),
AUTO_TIPO_CAJA decimal(18,0),
AUTO_TIPO_MOTOR_CODIGO decimal(18,0),
AUTO_TIPO decimal(18,0),
CONSTRAINT FK_AUTO_MODELO FOREIGN KEY (AUTO_MODELO) REFERENCES gd_esquema.Modelo(MODELO_CODIGO),
CONSTRAINT FK_AUTO_TIPO_TRANSMISION FOREIGN KEY (AUTO_TIPO_TRANSMISION) REFERENCES gd_esquema.Tipo_Transmision(TIPO_TRANSMISION_CODIGO),
CONSTRAINT FK_AUTO_TIPO_CAJA FOREIGN KEY (AUTO_TIPO_CAJA) REFERENCES gd_esquema.Tipo_Caja(TIPO_CAJA_CODIGO),
CONSTRAINT FK_AUTO_TIPO FOREIGN KEY (AUTO_TIPO) REFERENCES gd_esquema.Tipo_Auto(TIPO_AUTO_CODIGO)
);

CREATE TABLE gd_esquema.Auto_Parte (
AUTO_PARTE_CODIGO decimal(18,0) PRIMARY KEY,
AUTO_PARTE_DESCRIPCION nvarchar(255),
AUTO_PARTE_MODELO decimal(18,0),
CONSTRAINT FK_AUTO_PARTE_MODELO FOREIGN KEY (AUTO_PARTE_MODELO) REFERENCES gd_esquema.Modelo(MODELO_CODIGO)
);

CREATE TABLE gd_esquema.Tipo_Operacion (
TIPO_OPERACION_ID decimal(1,0) PRIMARY KEY,
TIPO_OPERACION_DESC nvarchar(50)
);

CREATE TABLE gd_esquema.Operacion (
OPERACION_NRO decimal(18,0),
OPERACION_TIPO decimal(1,0),
OPERACION_FECHA datetime2(3),
OPERACION_SUCURSAL decimal(18,0),
OPERACION_CLIENTE decimal(18,0),
OPERACION_PRECIO decimal(18,2),
PRIMARY KEY (OPERACION_NRO, OPERACION_TIPO),
CONSTRAINT FK_OPERACION_TIPO FOREIGN KEY (OPERACION_TIPO) REFERENCES gd_esquema.Tipo_Operacion(TIPO_OPERACION_ID),
CONSTRAINT FK_OPERACION_SUCURSAL FOREIGN KEY (OPERACION_SUCURSAL) REFERENCES gd_esquema.Sucursal(SUCURSAL_ID),
CONSTRAINT FK_OPERACION_CLIENTE FOREIGN KEY (OPERACION_CLIENTE) REFERENCES gd_esquema.Cliente(CLIENTE_ID)
);

CREATE TABLE gd_esquema.Item (
ITEM_OPERACION_NRO decimal(18,0) NOT NULL,
ITEM_OPERACION_TIPO decimal(1,0) NOT NULL,
ITEM_AUTO_ID decimal(18,0),
ITEM_AUTO_PARTE_ID decimal(18,0),
ITEM_CANTIDAD decimal(18,0) DEFAULT 1,
ITEM_PRECIO decimal(18,2) NOT NULL,
FOREIGN KEY (ITEM_OPERACION_NRO, ITEM_OPERACION_TIPO) REFERENCES gd_esquema.Operacion(OPERACION_NRO, OPERACION_TIPO),
CONSTRAINT FK_ITEM_AUTO FOREIGN KEY (ITEM_AUTO_ID) REFERENCES gd_esquema.Auto(AUTO_ID),
CONSTRAINT FK_ITEM_AUTO_PARTE FOREIGN KEY (ITEM_AUTO_PARTE_ID) REFERENCES gd_esquema.Auto_Parte(AUTO_PARTE_CODIGO)
);

CREATE INDEX IX_ITEM_OPERACION_AUTO ON gd_esquema.Item (ITEM_OPERACION_NRO,ITEM_OPERACION_TIPO,ITEM_AUTO_ID);
CREATE INDEX IX_ITEM_OPERACION_AUTO_PARTE ON gd_esquema.Item (ITEM_AUTO_PARTE_ID,ITEM_OPERACION_NRO,ITEM_OPERACION_TIPO);