--Creacion de estructuras
BEGIN
CREATE TABLE gd_esquema.Cliente (
CLIENTE_ID [numeric](18, 0) IDENTITY PRIMARY KEY,
CLIENTE_APELLIDO [nvarchar](255) NULL,
CLIENTE_NOMBRE [nvarchar](255) NULL,
CLIENTE_DIRECCION [nvarchar](255) NULL,
CLIENTE_DNI [decimal](18, 0),
CLIENTE_FECHA_NAC [datetime2](3) NULL,
CLIENTE_MAIL [nvarchar](255) NULL
);

CREATE TABLE gd_esquema.Sucursal (
SUCURSAL_ID [numeric](18, 0) IDENTITY PRIMARY KEY,
SUCURSAL_DIRECCION [nvarchar](255) NULL,
SUCURSAL_MAIL [nvarchar](255) NULL,
SUCURSAL_TELEFONO [decimal](18, 0) NULL,
SUCURSAL_CIUDAD [nvarchar](255) NULL
);

CREATE TABLE gd_esquema.Compra (
COMPRA_ID numeric(18,0) IDENTITY PRIMARY KEY,
COMPRA_FECHA datetime2(3),
COMPRA_NRO decimal(18,0),
COMPRA_PRECIO decimal(18,2),
COMPRA_CANT decimal(18,0)
);

CREATE TABLE gd_esquema.Tipo_Transmision (
TIPO_TRANSMISION_CODIGO decimal(18,0) PRIMARY KEY,
TIPO_TRANSMISION_DESC nvarchar(255)
);

CREATE TABLE gd_esquema.Tipo_Caja (
TIPO_CAJA_CODIGO decimal(18,0) PRIMARY KEY,
TIPO_CAJA_DESC nvarchar(255)
);

CREATE TABLE gd_esquema.Tipo_Auto (
TIPO_AUTO_CODIGO decimal(18,0) PRIMARY KEY,
TIPO_AUTO_DESC nvarchar(255)
);

CREATE TABLE gd_esquema.Fabricante (
FABRICANTE_ID numeric(18,0) IDENTITY PRIMARY KEY,
FABRICANTE_NOMBRE nvarchar(255) 
);

CREATE TABLE gd_esquema.Modelo (
MODELO_CODIGO decimal(18,0) PRIMARY KEY,
MODELO_NOMBRE nvarchar(255),
MODELO_POTENCIA decimal(18,0),
MODELO_FABRICANTE numeric(18,0) FOREIGN KEY REFERENCES gd_esquema.Fabricante(FABRICANTE_ID)
);

CREATE TABLE gd_esquema.Auto (
AUTO_ID numeric(18,0) IDENTITY PRIMARY KEY,
AUTO_NRO_CHASIS nvarchar(50),
AUTO_NRO_MOTOR nvarchar(50),
AUTO_PATENTE nvarchar(50),
AUTO_FECHA_ALTA datetime2(3),
AUTO_CANT_KMS decimal(18,0),
AUTO_MODELO decimal(18,0) FOREIGN KEY REFERENCES gd_esquema.Modelo(MODELO_CODIGO),
AUTO_TIPO_TRANSMISION decimal(18,0) FOREIGN KEY REFERENCES gd_esquema.Tipo_Transmision(TIPO_TRANSMISION_CODIGO),
AUTO_TIPO_CAJA decimal(18,0) FOREIGN KEY REFERENCES gd_esquema.Tipo_Caja(TIPO_CAJA_CODIGO),
AUTO_TIPO_MOTOR_CODIGO decimal(18,0),
AUTO_TIPO decimal(18,0) FOREIGN KEY REFERENCES gd_esquema.Tipo_Auto(TIPO_AUTO_CODIGO),
);

CREATE TABLE gd_esquema.Auto_Parte (
AUTO_PARTE_CODIGO decimal(18,0) PRIMARY KEY,
AUTO_PARTE_DESCRIPCION nvarchar(255),
AUTO_PARTE_MODELO decimal(18,0) FOREIGN KEY REFERENCES gd_esquema.Modelo(MODELO_CODIGO)
);

CREATE TABLE gd_esquema.Factura (
FACTURA_ID numeric(18,0) IDENTITY PRIMARY KEY,
FACTURA_FECHA datetime2(3),
FACTURA_NRO decimal(18,0),
FACTURA_SUCURSAL numeric(18,0) FOREIGN KEY REFERENCES gd_esquema.Sucursal(SUCURSAL_ID),
FACTURA_CLIENTE numeric(18,0) FOREIGN KEY REFERENCES gd_esquema.Cliente(CLIENTE_ID),
FACTURA_PRECIO decimal(18,2)
);

END
GO