-- Creacion de estructuras
CREATE TABLE gd_esquema.Cliente (
CLIENTE_ID [decimal](18, 0) IDENTITY PRIMARY KEY,
CLIENTE_APELLIDO [nvarchar](255) NULL,
CLIENTE_NOMBRE [nvarchar](255) NULL,
CLIENTE_DIRECCION [nvarchar](255) NULL,
CLIENTE_DNI [decimal](18, 0),
CLIENTE_FECHA_NAC [datetime2](3) NULL,
CLIENTE_MAIL [nvarchar](255) NULL
);

CREATE TABLE gd_esquema.Sucursal (
SUCURSAL_ID [decimal](18, 0) PRIMARY KEY,
SUCURSAL_DIRECCION [nvarchar](255) NULL,
SUCURSAL_MAIL [nvarchar](255) NULL,
SUCURSAL_TELEFONO [decimal](18, 0) NULL,
SUCURSAL_CIUDAD [nvarchar](255) NULL
);

CREATE TABLE gd_esquema.Tipo_Transmision (
TIPO_TRANSMISION_CODIGO decimal(18,0) PRIMARY KEY,
TIPO_TRANSMISION_DESC nvarchar(255)
);

CREATE TABLE gd_esquema.Tipo_Caja (
TIPO_CAJA_CODIGO decimal(18,0) PRIMARY KEY,
TIPO_CAJA_DESC nvarchar(255)
);

CREATE TABLE gd_esquema.Tipo_Auto (
TIPO_AUTO_CODIGO decimal(18,0) PRIMARY KEY,
TIPO_AUTO_DESC nvarchar(255)
);

CREATE TABLE gd_esquema.Fabricante (
FABRICANTE_ID decimal(18,0) IDENTITY PRIMARY KEY,
FABRICANTE_NOMBRE nvarchar(255) 
);

CREATE TABLE gd_esquema.Modelo (
MODELO_CODIGO decimal(18,0) PRIMARY KEY,
MODELO_NOMBRE nvarchar(255),
MODELO_POTENCIA decimal(18,0),
MODELO_FABRICANTE decimal(18,0),
MODELO_TIPO_TRANSMISION decimal(18,0),
MODELO_TIPO_CAJA decimal(18,0),
MODELO_TIPO_MOTOR decimal(18,0),
MODELO_TIPO_AUTO decimal(18,0),
CONSTRAINT FK_MODELO_FABRICANTE FOREIGN KEY (MODELO_FABRICANTE) REFERENCES gd_esquema.Fabricante(FABRICANTE_ID),
CONSTRAINT FK_MODELO_TIPO_TRANSMISION FOREIGN KEY (MODELO_TIPO_TRANSMISION) REFERENCES gd_esquema.Tipo_Transmision(TIPO_TRANSMISION_CODIGO),
CONSTRAINT FK_MODELO_TIPO_CAJA FOREIGN KEY (MODELO_TIPO_CAJA) REFERENCES gd_esquema.Tipo_Caja(TIPO_CAJA_CODIGO),
CONSTRAINT FK_MODELO_TIPO_AUTO FOREIGN KEY (MODELO_TIPO_AUTO) REFERENCES gd_esquema.Tipo_Auto(TIPO_AUTO_CODIGO)
);

CREATE TABLE gd_esquema.Auto (
AUTO_ID decimal(18,0) IDENTITY PRIMARY KEY,
AUTO_NRO_CHASIS nvarchar(50),
AUTO_NRO_MOTOR nvarchar(50),
AUTO_PATENTE nvarchar(50),
AUTO_FECHA_ALTA datetime2(3),
AUTO_CANT_KMS decimal(18,0),
AUTO_MODELO decimal(18,0),
CONSTRAINT FK_AUTO_MODELO FOREIGN KEY (AUTO_MODELO) REFERENCES gd_esquema.Modelo(MODELO_CODIGO)
);

CREATE TABLE gd_esquema.Autoparte (
AUTOPARTE_CODIGO decimal(18,0) PRIMARY KEY,
AUTOPARTE_DESCRIPCION nvarchar(255),
AUTOPARTE_MODELO decimal(18,0),
CONSTRAINT FK_AUTOPARTE_MODELO FOREIGN KEY (AUTOPARTE_MODELO) REFERENCES gd_esquema.Modelo(MODELO_CODIGO)
);

CREATE TABLE gd_esquema.Compra (
COMPRA_NRO decimal(18,0) PRIMARY KEY,
COMPRA_FECHA datetime2(3),
COMPRA_SUCURSAL decimal(18,0),
COMPRA_CLIENTE decimal(18,0),
COMPRA_PRECIO decimal(18,2),
CONSTRAINT FK_COMPRA_SUCURSAL FOREIGN KEY (COMPRA_SUCURSAL) REFERENCES gd_esquema.Sucursal(SUCURSAL_ID),
CONSTRAINT FK_COMPRA_CLIENTE FOREIGN KEY (COMPRA_CLIENTE) REFERENCES gd_esquema.Cliente(CLIENTE_ID)
);

CREATE TABLE gd_esquema.Factura (
FACTURA_NRO decimal(18,0) PRIMARY KEY,
FACTURA_FECHA datetime2(3),
FACTURA_SUCURSAL decimal(18,0),
FACTURA_CLIENTE decimal(18,0),
FACTURA_PRECIO decimal(18,2),
CONSTRAINT FK_FACTURA_SUCURSAL FOREIGN KEY (FACTURA_SUCURSAL) REFERENCES gd_esquema.Sucursal(SUCURSAL_ID),
CONSTRAINT FK_FACTURA_CLIENTE FOREIGN KEY (FACTURA_CLIENTE) REFERENCES gd_esquema.Cliente(CLIENTE_ID)
);

CREATE TABLE gd_esquema.Item_Compra_Auto (
ITEM_COMPRA_NRO decimal(18,0) NOT NULL,
ITEM_AUTO_ID decimal(18,0),
ITEM_CANTIDAD decimal(18,0) DEFAULT 1,
ITEM_PRECIO decimal(18,2) NOT NULL,
PRIMARY KEY (ITEM_COMPRA_NRO, ITEM_AUTO_ID),
FOREIGN KEY (ITEM_COMPRA_NRO) REFERENCES gd_esquema.Compra(COMPRA_NRO),
CONSTRAINT FK_ITEM_COMPRA_AUTO FOREIGN KEY (ITEM_AUTO_ID) REFERENCES gd_esquema.Auto(AUTO_ID)
);

CREATE TABLE gd_esquema.Item_Compra_Autoparte (
ITEM_COMPRA_NRO decimal(18,0) NOT NULL,
ITEM_AUTOPARTE_ID decimal(18,0),
ITEM_CANTIDAD decimal(18,0) DEFAULT 1,
ITEM_PRECIO decimal(18,2) NOT NULL,
PRIMARY KEY (ITEM_COMPRA_NRO, ITEM_AUTOPARTE_ID),
FOREIGN KEY (ITEM_COMPRA_NRO) REFERENCES gd_esquema.Compra(COMPRA_NRO),
CONSTRAINT FK_ITEM_COMPRA_AUTOPARTE FOREIGN KEY (ITEM_AUTOPARTE_ID) REFERENCES gd_esquema.Autoparte(AUTOPARTE_CODIGO)
);

CREATE TABLE gd_esquema.Item_Factura_Auto (
ITEM_FACTURA_NRO decimal(18,0) NOT NULL,
ITEM_AUTO_ID decimal(18,0),
ITEM_CANTIDAD decimal(18,0) DEFAULT 1,
ITEM_PRECIO decimal(18,2) NOT NULL,
PRIMARY KEY (ITEM_FACTURA_NRO, ITEM_AUTO_ID),
FOREIGN KEY (ITEM_FACTURA_NRO) REFERENCES gd_esquema.Factura(FACTURA_NRO),
CONSTRAINT FK_ITEM_FACTURA_AUTO FOREIGN KEY (ITEM_AUTO_ID) REFERENCES gd_esquema.Auto(AUTO_ID)
);

CREATE TABLE gd_esquema.Item_Factura_Autoparte (
ITEM_FACTURA_NRO decimal(18,0) NOT NULL,
ITEM_AUTOPARTE_ID decimal(18,0),
ITEM_CANTIDAD decimal(18,0) DEFAULT 1,
ITEM_PRECIO decimal(18,2) NOT NULL,
PRIMARY KEY  (ITEM_FACTURA_NRO, ITEM_AUTOPARTE_ID),
FOREIGN KEY (ITEM_FACTURA_NRO) REFERENCES gd_esquema.Factura(FACTURA_NRO),
CONSTRAINT FK_ITEM_FACTURA_AUTOPARTE FOREIGN KEY (ITEM_AUTOPARTE_ID) REFERENCES gd_esquema.Autoparte(AUTOPARTE_CODIGO)
);
